# Generated by Django 3.1.7 on 2021-03-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=480),
        ),
    ]
