# Generated by Django 3.1.7 on 2021-04-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210410_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=48, unique=True, verbose_name='nombre'),
        ),
    ]
